### PR TITLE
Fixed "Loading..." message on update

### PR DESCRIPTION
**Pull request by oncomouse**
This is a possible solution to the problem in #12 

The "Loading…" message that appears seems to be hanging around from earlier loads. As the actual React component (rather than the Chartkick object) only needs to update when `props.id` changes, creating the new Chartkick object in `shouldComponentUpdate` instead of `componentWillUpdate` prevents the erroneous loading message from appearing.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @oncomouse, thanks for the PR 👍 Do you have any sample code to reproduce the issue I can try out?

**Comment by Sexual** [comment]
Can we accept this pull request? It does appear to fix our issue.

**Comment by oncomouse** [comment]
I somehow missed @ankane's initial comment. Here's a repo that produces the initial issue for me: https://github.com/oncomouse/react-chartkick-example

**Comment by ankane** [comment]
Hey @oncomouse and @Sexual, can you try the `master` branch. After reading the React docs, I think `componentDidUpdate` is the correct hook we want to use.

**Comment by oncomouse** [comment]
@ankane, the `master` branch seems to fix this issue. 👍

**Comment by ankane** [comment]
Great, thanks for confirming. Just pushed a new release.

**Pull request closed without merging**
